import { test, expect } from '@playwright/test';
import { join } from 'node:path';
import { login, USERS } from './helpers';

/**
 * Admin → Data Import → Supplier Catalogue.
 *
 * The fixture is generated by `e2e/fixtures/make-workbook.mjs` and deliberately
 * reproduces the three things about the real template that break naive readers
 * — a header row that moves between sheets, `*` in header text, and semicolon
 * multi-value cells — plus four planted failures.
 */
const WORKBOOK = join(__dirname, 'fixtures', 'curation-template.xlsx');

test.describe('supplier catalogue import', () => {
  test('previews without writing, then applies', async ({ page }) => {
    test.setTimeout(120_000);
    await login(page, USERS.admin);
    await page.goto('/en/admin/imports');

    await page.getByTestId('catalogue-file').setInputFiles(WORKBOOK);
    // Apply is unavailable until a preview has been read.
    await expect(page.getByTestId('catalogue-import-apply')).toBeDisabled();

    await page.getByTestId('catalogue-import-preview').click();
    const summary = page.getByTestId('import-summary');
    await expect(summary).toBeVisible({ timeout: 60_000 });
    // Sheets 1, 2 and 6 carry an extra group-band row, so their headers sit one
    // row lower. A fixed-offset reader would read the band as headers.
    await expect(summary).toContainText('1. Company Master');
    await expect(summary).toContainText('6. Price Intelligence');

    // The planted failures, each named with a real Excel cell reference.
    const issues = page.getByTestId('import-issues');
    await expect(issues).toBeVisible();
    await expect(issues).toContainText("'1. Company Master'!F7");
    await expect(issues).toContainText('country not recognised');
    await expect(issues).toContainText("'2. API Products'!E7");
    await expect(issues).toContainText('CAS check digit failed');
    await expect(issues).toContainText('Company_ID is not in this file');

    // Personal-data columns are refused out loud, not silently dropped.
    const warnings = page.getByTestId('import-warnings');
    await expect(warnings).toContainText('personal-data column refused');

    // Preview wrote nothing.
    await page.goto('/en/admin/products');
    await expect(page.getByTestId('moderation-row').filter({ hasText: 'Kaveri' })).toHaveCount(0);

    // Apply.
    await page.goto('/en/admin/imports');
    await page.getByTestId('catalogue-file').setInputFiles(WORKBOOK);
    await page.getByTestId('catalogue-import-preview').click();
    await expect(page.getByTestId('import-summary')).toBeVisible({ timeout: 60_000 });
    await page.getByTestId('catalogue-import-apply').click();
    await expect(page.getByTestId('import-applied')).toBeVisible({ timeout: 60_000 });
    await expect(page.getByTestId('import-summary')).toContainText('created');
  });

  test('an imported company lands as a draft in the verification queue, never live', async ({ page }) => {
    test.setTimeout(120_000);
    // The single most dangerous confusion in this import: the template's
    // Verification Status is curation quality, not ops approval.
    await login(page, USERS.admin);
    await page.goto('/en/admin/imports');
    await page.getByTestId('catalogue-file').setInputFiles(WORKBOOK);
    await page.getByTestId('catalogue-import-preview').click();
    await expect(page.getByTestId('import-summary')).toBeVisible({ timeout: 60_000 });
    await page.getByTestId('catalogue-import-apply').click();
    await expect(page.getByTestId('import-applied')).toBeVisible({ timeout: 60_000 });

    // Not in the public catalogue — the org is a draft, so its listings are invisible.
    await page.goto('/en/catalog?q=Kaveri');
    await expect(page.getByTestId('product-card')).toHaveCount(0);
  });

  test('records the batch with its content hash', async ({ page }) => {
    test.setTimeout(120_000);
    await login(page, USERS.admin);
    await page.goto('/en/admin/imports');
    await page.getByTestId('catalogue-file').setInputFiles(WORKBOOK);
    await page.getByTestId('catalogue-import-preview').click();
    await expect(page.getByTestId('import-summary')).toBeVisible({ timeout: 60_000 });

    await page.reload();
    const row = page.getByTestId('import-batch-row').first();
    await expect(row).toContainText('curation-template.xlsx');
    await expect(row).toContainText('previewed');
  });

  test('refuses a file that is not a workbook, by its bytes', async ({ page }) => {
    // `file.type` is client-controlled and browsers send octet-stream for xlsx
    // anyway, so the check is the ZIP magic number.
    await login(page, USERS.admin);
    const res = await page.request.post('/api/admin/imports/supplier-catalogue', {
      multipart: { mode: 'preview', file: { name: 'evil.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: Buffer.from('MZ\x90\x00 not a zip') } },
    });
    expect(res.status()).toBe(415);
    expect((await res.json()).error).toBe('notXlsx');
  });

  test('is refused to anyone without moderation rights', async ({ page }) => {
    await login(page, USERS.seller);
    const res = await page.request.post('/api/admin/imports/supplier-catalogue', {
      multipart: { mode: 'preview', file: { name: 'x.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('PK\x03\x04') } },
    });
    expect(res.status()).toBe(403);
  });
});
